export { default as App } from './App';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Profile } from './Profile';
export { default as Store } from './Store'
export { default as Cart } from './Cart'
export { default as AddToCart } from "./AddToCart"
export { default as Home } from "./Home"
export { default as Loading } from "./Loading"
export { default as Checkout } from './Checkout'